'use server';

import { toApiError } from '@/lib/api/errors';
import { createSessionApiClient } from '@/lib/api/session-client';
import { requireOwner } from '@/lib/auth/current-account';
import type { FormState } from '@/lib/forms';

export interface QrCodeState extends FormState {
  // PNG data URL generated by the API, to be read in WhatsApp Business.
  qrCode?: string;
}

// CA-13.1: each call returns a fresh QR code for the barbershop number.
export async function requestQrCode(): Promise<QrCodeState> {
  await requireOwner();
  const api = await createSessionApiClient();
  const { data, error } = await api.POST('/whatsapp/connection');
  if (!data) return toApiError(error);
  return { qrCode: data.qrCode };
}
